### ISSUE TITLE
Can you please add a license to the repo?

### ISSUE THREAD

**Issue by JustinSpedding** [dhcrain/cl-clone#1]
Hello Davis.

I was looking around at some of the craigslist-like repos around Github and came across yours. I like it and wanted to fork it to use with some of my friends who did not want to deal with the shadiness of actual craigslist. But, I noticed that there is no license included in the repo. Is this intentional? It would be nice if you could add a something like the MIT, Apache, GPL etc. license file so that I can know if I can use it. Thank you!

From,
Justin

**Comment by dhcrain** [comment]
Sorry for the long delay in getting back to you. If it is not too late, please feel free to fork the repo. I have added a MIT licence.
